[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
anyhow = "1.0.100"
ash = "0.38.0"
bytemuck = "1.24.0"
ctrlc = "3.5.1"
glam = "0.30.9"
openxr = "0.19.0"
wgpu = "27.0.1"
indite = { path = "./crates/indite" }
